version: '3.4'

services:

  mongodb_dev:
    container_name: mongodb_dev
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

  redis_dev:
    container_name: redis_dev
    image: redis
    ports:
      - "6379:6379"

  postgresql_dev:
    container_name: postgresql_dev
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin_dev:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodb_dev:27017"
    depends_on:
      - mongodb_dev
    ports:
      - "8000:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=redis_dev:6379"
    depends_on:
      - redis_dev
    ports:
      - "8001:80"
